name: Detect act environment
description: 'Detects if the workflow is running in the act environment'
outputs:
  is_act:
    description: "True if running in act, false otherwise"
    value: ${{ steps.detect_act.outputs.is_act }}
runs:
  using: "composite"
  steps:
    - name: Detect act environment
      id: detect_act
      shell: bash
      run: |
        if [ "${{ github.actor }}" = "nektos/act" ] || [ "${ACT:-}" = "true" ] || [ "${ACT:-}" = "1" ]; then
          echo "is_act=true" >> $GITHUB_OUTPUT
        else
          echo "is_act=false" >> $GITHUB_OUTPUT
        fi
